language: ruby
cache:
  bundler: true
  directories:
    - tmp/solr_downloads
dist: trusty
sudo: false
jdk:
  - oraclejdk8
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ursus_test;'
env:
  global:
    - DATABASE_USERNAME=travis
    - secure: "N7Xkgo7xtlzPeZoGMC8cQ+EL6dB6GjKhhx9dTcnAMu3zdod/5Eqbgmxn+FuYu7AuqBN9cPhFsAiDwjxPSla5CTKndtbNVnNOTsnNjpznC5xYLclRY4XdPlwNVzsfX43bSqlBGQnNO8GmjwyMycETxlkHNAZzhkbVaY5GTdolAKwyl4ak4wAxMDI1iyAY0So3YpkS9ZOVYXdnnS3SqatP4aJOMzs28Idfa7LUKVoRWGTU2x5v+LUj+R4uPykV0A7CPQ/c12TWOfktIY+N/y7vWcGzxT2xLzAD4wUZFI8ST4NiF6/aUg4bJCsMicz6Mzvs00TN5KQaLSHg1mte7H5J9NM+RIyAgH6GJFj80e8Q/Sh3zYZeoF5uA/5NDdGrd0hYksMISjXiz2Haa0Z1+/MwAzOnpP98hX7XRb36MR3W6l1R4PQ695T7ZTOGl08um1DpvHDPt5NQbrwUZVjLcVELRIlRENvawDQ76Y2icH0dKPeTAA34R7CCPGhl5XCHcrA3fgFzpNhLUMxsJdJgGRNDQXqwF+xO7uVr9Q8PxPOfxprv31WuTHn189FlCI63XYlh1BcTj3jXQsM9/cqUzQ1BwFPsJA9rogmOeIiDGHdM6Aq7xRUqaoe/7ZX1WM9JVletipLjFSJRniIdhJ/AvwUNBiybk+N6bl/oor/tTSLpy/Y="
    - secure: "JorGctqrB1BDqbNQSy9WVPEFMlxF8pFU4PFXFzIiulYMCUJ+eUlI27v9BfZ+iXJuYLgU9pvW3Mygnfz2GBvTlgqn56B414tMuJyU6ie1fx4vPAfpFFo43Px2R9QZq0OkqT6MPDTOKFNeGTpZkPg96Rz9UtMrR2olC8eRlRSuXwmmEplBueUleWTWyheSWM/ax+1V2QRD1ku9RBggbIuQO+sF9YqEb5IiBeaQ0GPTwt/YVtSeyyKghM2Yi0INjm7sgl6PZDlmG8EKiLsdCjQeXqK9F0L6+qujjjHsB3ONVxnvTLJfndMuM/di+UjyBRI5+/9eNkVXkdlUX+ve4h9TmWYBXnP5dxKmvbE3JSFTfgEKTE8edHp9r+tV4UgGLr5e7iCjonVEIISpNzjEsEDQruWVuk6/Dje4D3IPI41E+MO2Wd5HJep6/d1Umz6pLuLeRDS+mgVhBmMpNpRSmhGU0B1Pj8+vx7tY2hjwT9001txWpKCO9V/vLWQlWSdEmKjFCCAUhivku24qZSO5jj9saHUYKQDEelamKiW2gfZOBykuyfszWgoZfm4kRmw02tPZkxaAe9pM8Lgt75kL65uUuKaUGO+k9JyihA0pZNOGmFKOugwNz49TgWZzJ31ZwSNdRFi1Y65nSWg89vU6/8CCAh2+bmfy2MRw4JX++ZqhJtY="
rvm:
  - 2.5.1
script:
  - bundle exec rake ci
notifications:
  email: false
services:
  - mysql2
after_success:
- |
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    curl "$JENKINS_DEPLOY_URL"
  fi
  if [[ $TRAVIS_TAG =~ ^sprint[0-9]*\.rc[0-9]* ]]; then
    echo "$TRAVIS_TAG"
    curl "$JENKINS_TAG_DEPLOY_URL"
  fi
