language: ruby
cache:
  bundler: true
  directories:
    - tmp/solr_downloads
dist: trusty
sudo: false
jdk:
  - oraclejdk8
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ursus_test;'
env:
  global:
    - DATABASE_USERNAME=travis
rvm:
  - 2.5.1
script:
  - bundle exec rake ci
notifications:
  email: false
services:
  - mysql2
