services:
  sinai:
    # image: uclalibrary/sinaimanuscripts:latest
    build: .
    stdin_open: true
    tty: true
    command: "sh start-sinai.sh"
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_started
    env_file:
      - ./default.env
      - ./docker.env
    ports:
      - "127.0.0.1:3004:3000"
    volumes:
      - .:/sinai
      - node_modules:/sinai/node_modules
      - tmp:/sinai/tmp
    working_dir: /sinai

  db:
    image: uclalibrary/californica-mariadb:10.3
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  solr:
    image: uclalibrary/solr-ursus
    ports:
      - "127.0.0.1:8983:8983"

  solr_test:
    image: uclalibrary/solr-ursus
    ports:
      - "127.0.0.1:8985:8983"
  
  load:
    build:
      dockerfile: ./solr/Dockerfile.loader
    depends_on:
      - solr
    env_file:
      - docker.env
    volumes:
      - ./solr/sinaiportal_data:/data

volumes:
  mysql_data:
  node_modules:
  tmp:
