# These fields are in order of display

# Sinai only - Codicology
format_extent_tesim: 'Extent'

folio_dimensions_ss: 'Typical Folio Dimensions'
form_tesim: 'Form'
support_tesim: 'Support'
writing_system_tesim: 'Writing system'
script_tesim: 'Script'
script_note_tesim: 'Script Note'
scribe_tesim: 'Scribe'
hand_note_tesim: 'Hand Note'
ink_color_tesim: 'Ink Color'
page_layout_ssim: 'Page Layout'
foliation_tesim: 'Foliation'
collation_tesim: 'Collation'
condition_note_tesim: 'Condition Note'
binding_note_tesim: 'Binding Note'
description_tesim: 'Physical Description note'
