# These fields are in order of display

# Sinai only - History
date_created_tesim: 'Date created'
place_of_origin_tesim: 'Place of Origin'
colophon_tesim: 'Colophon'
provenance_tesim: 'Provenance'
inscription_tesim: 'Inscriptions'
overtext_manuscript_ssm: 'Overtext manuscript'
related_tesim: 'Related Items'
