# These fields are in order of display

# Sinai only - Overview
place_of_origin_tesim: 'Place of origin'
date_created_tesim: 'Date created'
format_extent_tesim: 'Extent'
form_tesim: 'Form'
human_readable_language_tesim: 'Language'
writing_system_tesim: 'Writing system'
script_tesim: 'Script'
repository_tesim: 'Repository'
collection_tesim: 'Collection'
human_readable_rights_statement_tesim: 'Rights statement'
services_contact_ssm: 'Rights contact'
