# These fields are in order of display

# Sinai only - Overview
repository_ssim: 'Location'
collection_ssim: 'Collection'
state_ssi: 'Current State'
place_of_origin_tesim: 'Origin'
ot_date_tesim: 'Date of Origin'
ot_script_ssim: 'Scripts'
ot_language_ssim: 'Languages'
extent_tesi: 'Extent'
format_extent_tesim: 'Extent'
foliation_tesim: 'Foliation'
collation_tesim: 'Collation'
