human_readable_rights_statement_tesim: 'Rights statement'
rights_country_tesim: 'Rights (country of creation)'
rights_holder_tesim: 'Rights Holder'
services_contact_ssm: 'Rights Contact'
license_tesim: 'License'
funding_note_tesim: 'Funding Note'
