alternative_title_tesim: 'Alternative Title'
architect_tesim: 'Architect'
author_tesim: 'Author'
colophon_tesim: 'Colophon'
composer_tesim: 'Composer'
contents_note_tesim: 'Contents note'
date_created_tesim: 'Date Created'
dlcs_collection_name_tesim: 'Collection (native)'
explicit_tesim: 'Explicit'
human_readable_language_tesim: 'Language'
illuminator_tesim: 'Illuminator'
incipit _tesim: 'Incipit'
lyricist_tesim: 'Lyricist'
member_of_collections_ssim: 'Collection'
normalized_date_sim: 'Date'
photographer_tesim: 'Photographer'
place_of_origin_tesim: 'Place of Origin'
publisher_tesim: 'Publisher'
scribe_tesim: 'Scribe'
title_tesim: 'Title'
uniform_title_tesim: 'Uniform title'
year_isim: 'Year'
