title_tesim: 'Title'
alternative_title_tesim: 'Alternative Title'
member_of_collections_ssim: 'Collection'
uniform_title_tesim: 'Uniform title'
photographer_tesim: 'Photographer'
architect_tesim: 'Architect'
date_created_tesim: 'Date Created'
normalized_date_sim: 'Date'
year_isim: 'Year'
place_of_origin_tesim: 'Place of Origin'
publisher_tesim: 'Publisher'
human_readable_language_tesim: 'Language'
dlcs_collection_name_tesim: 'Collection (native)'
illuminator_tesim: 'Illuminator'
scribe_tesim: 'Scribe'
lyricist_tesim: 'Lyricist'
composer_tesim: 'Composer'
