format_tesim: 'Format'
medium_tesim: 'Medium'
support_tesim: 'Support'
extent_tesim: 'Extent'
dimensions_tesim: 'Dimensions'
page_layout_ssim: 'Page layout'
binding_note_ssi: 'Binding note'
collation_ssi: 'Collation'
illustrations_note_tesim: 'Illustrations note'
foliation_ssi: 'Foliation'
inscription_tesim: 'Inscription'
script_tesim: 'Script'
writing_and_hands_tesim: 'Writing and hands'
writing_system_tesim: 'Writing system'
condition_note_tesim: 'Condition note'
