binding_note_tesim: 'Binding note'
collation_tesim: 'Collation'
condition_note_tesim: 'Condition note'
dimensions_tesim: 'Dimensions'
extent_tesim: 'Extent'
foliation_tesim: 'Foliation'
format_tesim: 'Format'
illustrations_note_tesim: 'Illustrations note'
inscription_tesim: 'Inscription'
medium_tesim: 'Medium'
page_layout_ssim: 'Page layout'
script_tesim: 'Script'
support_tesim: 'Support'
writing_and_hands_tesim: 'Writing and hands'
writing_system_tesim: 'Writing system'
