date_created_tesim: 'Date Created'
language_tesim: 'Language'
publisher_tesim: 'Publisher'
member_of_collections_ssim: 'Collection'
dlcs_collection_name_tesim: 'Collection'
date_uploaded_tesim: 'Date Uploaded'
date_modified_tesim: 'Date Modified'
