repository_tesim: 'Repository'
funding_note_tesim: 'Funding Note'
rights_country_tesim: 'Rights Country'
rights_holder_tesim: 'Rights Holder'
license_tesim: 'License'
identifier_tesim: 'Identifier'
local_identifier_tesim: 'Local Identifier'
