repository_tesim: 'Repository'
funding_note_tesim: 'Funding Note'
rights_country_tesim: 'Rights Country'
rights_holder_tesim: 'Rights Holder'
license_tesim: 'License'
identifier_tesim: 'Identifier'
local_identifier_ssm: 'Local Identifier'
ark_ssi: 'ARK'
services_contact_ssm: 'Rights services contact'
human_readable_rights_statement_tesim: 'copyrighted'
