subject_tesim: 'Subject'
named_subject_tesim: 'Named Subject'
keyword_tesim: 'Keyword'
based_near_label_tesim: 'Based Near'
location_tesim: 'Location'
geographic_coordinates_ssim: 'Geographic Coordinates'
