name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Dockerhub
      uses: docker/build-push-action@9379083e426e2e84abb80c8c091f5cdeb7d3fd7a
      with:
        push: true
        tags: uclalibrary/sinaimanuscripts:latest
        tag_with_ref: true
