name: Build Docker Image

on:
  pull_request:
    branches: [ main ]

jobs:

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Dockerhub
      uses: docker/build-push-action@v1
      with:
        push: true
        repository: uclalibrary/sinaimanuscripts
        tag_with_ref: true
