name: Build with tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  jenkins-build:
    name: Deploys new release to stage
    runs-on: ubuntu-latest
    steps:
     - name: Tag name
       id: extract_tag
       run: | 
         echo "VERSION_TAG=${GITHUB_REF##*/}" >> "$GITHUB_ENV"
     - name: Jenkins webhook
       uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
       with:
         curl: 'https://${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_AUTH_TOKEN }}@${{ secrets.JENKINS_HOST }}/job/DeploySinai/buildWithParameters?GIT_BRANCH=${VERSION_TAG}&cause=GitHub+Action+Build+with+tag&DEPLOY_HOST=s-w-sinaimanuscripts01.library.ucla.edu'
